config/routes.rb
Rails.application.routes.draw do
  root 'static#home'

  resources :albums 
  resources :users do
    resources :album_users, :albums 
  end

  resources :albums do
    member do
      delete :delete_image_attachment
    end
  end

  get '/signin', to: "session#signin"
  post '/signin', to: "session#create"
  get '/logout', to: "session#destroy"
  
end

app/models/album.rb
class Album < ApplicationRecord
    has_many :album_users
    has_many :users, through: :album_users

    has_many_attached :images do |attachable|
        attachable.variant :thumb, resize: "100x100"
    end
     
end

app/models/album_user.rb
class AlbumUser < ApplicationRecord
    belongs_to :user
    belongs_to :album
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :album_users
    has_many :albums, through: :album_users

    has_secure_password
    validates :username, :email, :password_digest, presence: true, uniqueness: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_login

  # GET /albums or /albums.json
  def index
    @user = User.find(params[:user_id])
    if @user == current_user
      @albums = @user.albums 
    else
      redirect_to root_path    
    end
  end

  # GET /albums/1 or /albums/1.json
  def show
    set_album
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
    set_album
  end

  # POST /albums or /albums.json
  def create
    @album = Album.new(album_params)
    @album.users << current_user
    params[:user_ids] do |id|
      @album.users << User.find_by(id: id)
    end

    respond_to do |format|
      if @album.save 
        format.html { redirect_to user_albums_path(current_user), notice: "Album was successfully created." }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1 or /albums/1.json
  def update
    set_album
    respond_to do |format|
      if @album.update(album_params)
        @album.users << current_user
        format.html { redirect_to @album, notice: "Album was successfully updated." }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1 or /albums/1.json
  def destroy
    @album = set_album
    @album.images.purge 
    respond_to do |format|
      if @album.destroy 
        format.html { redirect_to user_albums_path(@album.user), notice: "Album was successfully deleted." }          
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # Custom action for deleting single images
  def delete_image_attachment
    @image = ActiveStorage::Attachment.find(params[:id])
    @image.purge
    redirect_to user_albums_path(current_user)
  end

  private
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:title, images: [], user_ids: [])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    helper_method :current_user, :logged_in?
    
    def current_user
        User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !!current_user
    end

    def require_login
        if current_user 
            current_user
        else 
            redirect_to root_path
        end 
    end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

        def new  
        end
    
        def create
            @user = User.find_by(username: params[:username]) 
            if @user && @user.authenticate(params[:password])
                session[:user_id] = @user.id 
                redirect_to user_path(@user)
            else
                render :signin
            end
        end
    
        def destroy
            session.delete("user_id") 
            redirect_to root_path
        end
    
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def home 
    end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:new, :create]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save && @user.valid?
            session[:user_id] = @user.id 
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def show
        @user = User.find_by(id: params[:id])
    end

    def edit
        @user = User.find_by(id: params[:id])
    end

    def update 
        @user = User.find_by(id: params[:id])
        if @user
            @user.update(user_params)
            redirect_to user_path(@user)
        else
            redirect_to root_path
        end
    end

    private
    
    def user_params
        params.require(:user).permit(
            :username, 
            :email, 
            :password, 
            :password_confirmation
        )
    end    
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<%= form_with(model: album, local: true) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% album.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div class="field">
    <%= form.label :users %>
    <%= form.collection_check_boxes :user_ids, User.all.select {|user| user != current_user}, :id, :username %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Show Album', @album %> 

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>


<% if logged_in? %>
    <h2><%= current_user.username %>'s Albums</h2>
    <% if !@albums.empty? %>
        <% @albums.each do |album| %>
            <%= link_to album.title, album_path(album) %>
            <%= button_to 'Delete Album', album_path(album), method: :delete, data: { confirm: "Are you sure you want to delete this album?" } %>  
    <br/>
        <% end %>
    <% else %>
        <p>The user has no albums</p>
    <% end %>
    <br>

    <%= link_to 'New Album', new_album_path %>
<% end %> 

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form', album: @album %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @album.title %>
</p>

<p>
  <strong>User:</strong>
  <%= current_user.username %>
</p>

<p>
  <strong>Images:</strong>
  <br>
  <% if @album.images.attached? %>
    <% @album.images.each do |image| %>
      <%= image_tag image, width: "200px" %>
      <%= button_to 'Remove Image', delete_image_attachment_album_path(image), method: :delete, data: {confirm: "Are you sure?"} %>
    <% end %>
  <% end %>
</p>

<%= link_to 'Edit Album', edit_album_path(@album) %>
<%= button_to 'Delete Album', @album, :method => :delete, data: { confirm: "Are you sure you want to delete this album?" } %>  
<%= link_to "Back to My Albums", user_albums_path(current_user) %><br/>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShopifyBackEndChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>

  <body>
    <% if logged_in? %>
      <ul class="nav justify-content-center border bg-dark">
        <li class="nav-item">
          <a class="nav-link p-4" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link p-4" href="<%= user_path(current_user) %>">My Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link p-4" href="<%= logout_path %>">Log Out</a>
        </li>  
      </ul>
    <% end %>

    <div class = "container p-4"> 
        <%= yield %>
    <br/>

    </div>    
  </body>
</html>

app/views/session/signin.html.erb
<h2>Sign In</h2>

<%= form_tag "/signin", method: :post do |f| %>
    <%= label_tag :username %>
    <%= text_field_tag :username %>

    <%= label_tag :password %>
    <%= text_field_tag :password %>

    <%= label_tag :password_confirmation %>
    <%= text_field_tag :password_confirmation %>

    <%= submit_tag "Sign In"%>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.text_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<% if logged_in? %>
  <p>
    <strong>Username:</strong>
    <%= current_user.username %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= current_user.email %>
  </p>

  <%= link_to "See My Albums", user_albums_path(current_user) %><br/>
  <%= link_to "Create a New Album", new_user_album_path(current_user) %><br/>
  <%= link_to 'Edit Profile', edit_user_path(current_user) %> 
<% end %>  